name: Release a new Lect version

on:
  push:
    tags: 
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Create Release
      id: create_release
      uses: comnoco/create-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref_name }}
        body: Github Actions release
        draft: false
        prerelease: false
