name: Release on push to tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install necessary packages
        run: sudo apt update && sudo apt install cmake clang-18 pkg-config mingw-w64

      - name: Create build dir
        run: mkdir build && rm -r build/*

      - name: Run CMake for Windows with MINGW
        run: cmake -S . -B build/ -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_TOOLCHAIN_FILE=~/mingw-w64-x86_64.cmake -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DCMAKE_GENERATOR='MinGW Makefiles' -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32 -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY

      - name: Compile for Windows with MINGW
        run: cd build && make

      - name: Debug
        run: ls -la build

      - name: Move executable
        run: mv build/lect.exe lect-win.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with: 
          files: |
            lect-linux
            lect-win.exe
