name: Release a new Lect version

on:
  push:
    tags: 
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: Install necessary packages
      run: sudo apt update && sudo apt install cmake clang-18 pkg-config

    - name: Run CMake
      run: mkdir build && cmake -S . -B build/ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Compile
      run: cd build && make

    - name: Create Release
      id: create_release
      uses: comnoco/create-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Lect ${{ github.ref }}
        body: Automatic release
        draft: false
        prerelease: false
