name: Release on push to tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install necessary packages
        run: sudo apt update && sudo apt install cmake clang-18 pkg-config mingw-w64

      - name: Run CMake for Linux
        run: mkdir build && cmake -S . -B build/ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Compile for Linux
        run: cd build && make

      - name: Move executable
        run: mv build/lect lect-linux

      - name: Create build dir
        run: mkdir build-win

      - name: Run CMake for Windows with MINGW
        run: cmake --fresh -S . -B build-win/ -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32 -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY

      - name: Compile for Windows with MINGW
        run: cd build-win && make

      - name: Move executable
        run: mv build-win/lect.exe lect-win.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with: 
          files: |
            lect-linux
            lect-win.exe
